name: my_review
description: "A new Flutter project."
publish_to: "none"

version: 1.0.1+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.0
  shared_preferences: ^2.2.0
  device_info_plus: ^10.0.0
  url_launcher: ^6.3.1
  flutter_background_service: ^5.0.0
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.2
  permission_handler: ^11.0.0
  # حذفت flutter_launcher_icons من هنا لأن مكانها الصحيح في الأسفل

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  flutter_launcher_icons: ^0.13.1
  package_info_plus: ^8.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/quiz/6th/
    - assets/icon/icon.png

# إعدادات الأيقونة (تأكد أن الصورة موجودة في هذا المسار)
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"